### ISSUE TITLE
Download bought content from the messages section of a specific model?

### ISSUE THREAD

**Issue by waswosi** [Voldrix/onlyfans-dl-2#18]
It works just wonderful!
But I thought it does download bought content from the messages section of a specific model too.
But It seems it does not.
Any help?

**Comment by Voldrix** [comment]
It does download purchased content, as long as the purchased variable is set to true at the top of the script.
I did however just merge a patch relating to the messages, this might fix your issue. Give the latest commit a try.

**Comment by MyNameIsJustBob** [comment]
I have the same issue, just tried the latest commit and it now recognises the purchased items but doesn't download them. I've checked and download purchased is definitely set to True

**Comment by Voldrix** [comment]
I can't seem to reproduce this error, but I only have a few purchased posts. I'm thinking this could be an issue with the max number of purchased posts per API call being lower than other message types. Since I don't really have a way of testing this, could you do me a favor and on line 75, set posts_limit = 10 instead of 100, and run the script again and see if you get the missing purchased posts.

**Comment by MyNameIsJustBob** [comment]
Thanks, I've tried amending it. It still finds the purchased items but doesn't download them, sadly

**Comment by MyNameIsJustBob** [comment]
I've just realised that it says 'Found 133 purchased' no matter which profile I select

**Comment by Voldrix** [comment]
The purchased API call is not profile specific, so it will show you the total but then only download ones for the profile you selected. The profile you're downloading, does that one have purchased posts?

**Comment by MyNameIsJustBob** [comment]
Ah I see, yes it does

**Comment by waswosi** [comment]
Sorry I got it wrong. I works just perfectly. Tool looks for all your purchased content and only downloads if it belongs to the specific model you entered.
