### ISSUE TITLE
ERROR: Wrong user

### ISSUE THREAD

**Issue by GeoGenesis** [Voldrix/onlyfans-dl-2#2]
Getting the following error:

`ERROR: Wrong user.`

Is this indicating that the user-id is incorrect in the .py or can the script not find the page that I am trying to send it to?
I tried:

- py onlyfans-dl.py targetUsername
- py onlyfans-dl.py @targetUsername
- py onlyfans-dl.py /targetUsername

And all led to failures.

**Comment by bnsave100** [comment]
@GeoGenesis tried on multiple profiles ??

**Comment by Voldrix** [comment]
That refers to your own user-id in the script. Make sure it is correct by checking the request headers in the developer console when your browser makes a request to a json file on the site.

**Comment by pippopelo56** [comment]
Wrong User for me too.

**Comment by GeoGenesis** [comment]
![chrome_S9Hs1XVr38](https://user-images.githubusercontent.com/11330683/118160617-70390f80-b416-11eb-91aa-99baa42d61dc.png)

@Voldrix - is it not this value? This is what I have in the .py file.

**Comment by GeoGenesis** [comment]
> @GeoGenesis tried on multiple profiles ??

Tested on 2 different accounts with the same methodology. Same error when it resolved.

**Comment by Voldrix** [comment]
So that is the correct user-id. The only thing I can think of is double checking the other variables. I just tested the script on a second account of mine, and it seems to be working. So if this doesn't fix it I don't know what the issue would be. All four of these values have to be set exactly like this, and updated each time you login. The cookie header needs the "sess=" part.
```
"user-id": "123456789",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
"x-bc": "95d3er4th7jx8c2dcsd5g8uin9a2gt5ca8bba8167",
"Cookie": "sess=eav1th8io0pde2ksf6qb"
```
and for the profile name, you just need the username without any special symbols.

People over on digitalcriminal's page still seem to be reporting intermittent issues with the signing definitions. It seems like OF might be changing these dynamically on a periodic basis. Not sure yet if that is true, but doesn't really explain why it works for some people and not others.

**Comment by GeoGenesis** [comment]
@Voldrix I think you might have shown me the answer:

`"Cookie": "sess=eav1th8io0pde2ksf6qb"`

It is not clear that we needed to keep the "sess=" component of the Cookie. I only copied the sessionId value.

Changing it to this fixed the problem, thank you!

**Comment by Voldrix** [comment]
Okay cool. I think I'll create a config file for these values so you don't have to worry about things like that in the future.
