### ISSUE TITLE
profiles directory

### ISSUE THREAD

**Issue by BerserkRaged** [Voldrix/onlyfans-dl-2#7]
Hi, I'm pretty new to github so I'm unsure if there is another place for a simple discussion as this may not be an actual issue per say.

But I've set this up and it's working well. The only problem I have at the moment is that in some of the guides written it seems like content is supposed to be donwnloaded to "/topdir(script here)/profiles/onlyfansaccountname/". Currently I execute the script at the top directory and it saves everything in the same directory for example "/topdir/onlyfansaccountname/". It's really not a big concern I was just curious why mine might not be working properly.

The only lines I changed in the script were in the Options and Session Variables.

Thanks.

**Comment by Voldrix** [comment]
Any guides that stated that directory structures were for the original version, my fork is a far departure from the original with only a few lines left in common. At the top of the readme it states that the profile name directory is created in the current working directory. This is because I didn't like having an extra subdirectory to transcend. So if you want that extra subdirectory, you can create it and then move into that directory before running the script and you'll get the same effect.

**Comment by Voldrix** [comment]
Also I just added the discussions tab to this repo.

**Comment by BerserkRaged** [comment]
Awesome, thank you for the quick response. I don't prefer it one way over the other really. Just glad someone has these scripts working like a charm.

Thanks again.
